### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Conte-harebourd** [manekinekko/digital-covid-certificate-decoder#1]
![image](https://user-images.githubusercontent.com/51010031/128423627-b5f6d235-e40c-4312-9ada-79fcb5186f25.png)
Impossible de décodé

**Comment by manekinekko** [comment]
Visiblement ce pass sanitaire a été encodé avec une version du protocole HC1 differente de `v0.0.4`, comme indiqué dans le message d'erreur. Donc, il n'est pas possible de le décoder pour le moment.

**Comment by Conte-harebourd** [comment]
Ah d'accord merci du retour

**Comment by onelots** [comment]
Ouep, j'ai le même problème :/
